### ISSUE TITLE
Нет первой задачи

### ISSUE THREAD

**Issue by vp1981** [EniseevS/geant4#1]
Нет файла с решение первой задачи

**Comment by vp1981** [comment]
Решение последующих задач предполагает наличие самой первой задачи.

Вторую задачу можно решить добавив код в решение первой.

**Comment by EniseevS** [comment]
Все понял, сегодня постараюсь вдумчиво исправить код.-- С уважением, Енисеев С. А. +7(924) 546-98-8805.12.2023, 08:01, "Vladimir Lomov" ***@***.***>:
Решение последующих задач предполагает наличие самой первой задачи.
Вторую задачу можно решить добавив код в решение первой.

**Comment by vp1981** [comment]
Привет.

Так ничего и не изменилось. Код остался прежним.

**Comment by vp1981** [comment]
Задание есть, но сфера помещена в «мир», а должны быть в «контейнере».

**Comment by vp1981** [comment]
Есть
